// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderManagement.Infrastructure.Persistence;

#nullable disable

namespace OrderManagement.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428084928_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderManagement.Domain.Entities.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CatalogDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MerchantId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ScheduledPublishAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WhatsAppMessageTemplate")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.ToTable("Catalogs", "Order");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CatalogId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("ProductId");

                    b.ToTable("CatalogItems", "order");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories", "order");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 232, DateTimeKind.Local).AddTicks(9451),
                            Name = "Batters"
                        },
                        new
                        {
                            Id = 2,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 234, DateTimeKind.Local).AddTicks(2760),
                            Name = "Accompaniments"
                        },
                        new
                        {
                            Id = 3,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 234, DateTimeKind.Local).AddTicks(2775),
                            Name = "Ready to Eats"
                        },
                        new
                        {
                            Id = 4,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 234, DateTimeKind.Local).AddTicks(2776),
                            Name = "Tiffin Items"
                        },
                        new
                        {
                            Id = 5,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 234, DateTimeKind.Local).AddTicks(2777),
                            Name = "Podis"
                        },
                        new
                        {
                            Id = 6,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 234, DateTimeKind.Local).AddTicks(2778),
                            Name = "Add Ons"
                        },
                        new
                        {
                            Id = 7,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 234, DateTimeKind.Local).AddTicks(2779),
                            Name = "Sweet & Namkeen"
                        });
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.CustomerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Block")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FlatOrVillaNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastOrderAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MerchantSocietyId")
                        .HasColumnType("integer");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("WhatsAppId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MerchantSocietyId");

                    b.HasIndex("UserId", "MerchantSocietyId")
                        .IsUnique();

                    b.ToTable("CustomerProfiles", "user");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.DeliverySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("MaxDeliveryCharge")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MaxParcelCharge")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MinDeliveryCharge")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MinParcelCharge")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("DeliverySettings", "order");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 245, DateTimeKind.Local).AddTicks(1906),
                            MaxDeliveryCharge = 40m,
                            MaxParcelCharge = 15m,
                            MinDeliveryCharge = 25m,
                            MinParcelCharge = 5m
                        });
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.ExceptionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("StatusCode");

                    b.HasIndex("Timestamp");

                    b.HasIndex("StatusCode", "Timestamp");

                    b.ToTable("ExceptionLogs", "error");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("AdminUserId")
                        .HasColumnType("integer");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WhatsAppNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.ToTable("Merchants", "user");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.MerchantSociety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeliveryInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MerchantId")
                        .HasColumnType("integer");

                    b.Property<int>("SocietyId")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SocietyId");

                    b.HasIndex("MerchantId", "SocietyId")
                        .IsUnique();

                    b.ToTable("MerchantSocieties", "user");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CatalogId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomerBlock")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CustomerFlatVilla")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("MerchantSocietyId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("RawMessage")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddedDate")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("CatalogId");

                    b.HasIndex("MerchantSocietyId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("Status")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", "order");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", "order");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.OrderStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusHistories", "order");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.OrderTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomFieldsJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("MerchantId")
                        .HasColumnType("integer");

                    b.Property<bool>("RequireBlock")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireFlatVilla")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireMobile")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireName")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireSociety")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireWhatsApp")
                        .HasColumnType("boolean");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId", "IsDefault")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = true");

                    b.ToTable("OrderTemplates", "order");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("INR");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LinkExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PaymentLinkId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PaymentLinkUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RazorpayOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RazorpayPaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentLinkId");

                    b.ToTable("Payments", "order");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PresentCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("RevisedCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", "order");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 243, DateTimeKind.Local).AddTicks(9485),
                            CategoryId = 1,
                            Name = "Idly Dosa Batter",
                            PresentCost = 70m,
                            Quantity = "1 kg"
                        },
                        new
                        {
                            Id = 2,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2058),
                            CategoryId = 1,
                            Name = "Appam Batter",
                            PresentCost = 100m,
                            Quantity = "1 kg"
                        },
                        new
                        {
                            Id = 3,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2065),
                            CategoryId = 1,
                            Name = "4 Millets",
                            PresentCost = 140m,
                            Quantity = "1 kg"
                        },
                        new
                        {
                            Id = 4,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2067),
                            CategoryId = 1,
                            Name = "Pesarat Dosa",
                            PresentCost = 120m,
                            Quantity = "1 kg"
                        },
                        new
                        {
                            Id = 5,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2069),
                            CategoryId = 1,
                            Name = "Rava Dosa",
                            PresentCost = 100m,
                            Quantity = "1 kg"
                        },
                        new
                        {
                            Id = 6,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2071),
                            CategoryId = 1,
                            Name = "Paddu / Paniyaram Batter",
                            PresentCost = 120m,
                            Quantity = "1 kg"
                        },
                        new
                        {
                            Id = 7,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2072),
                            CategoryId = 1,
                            Name = "Udin Vada Batter",
                            PresentCost = 100m,
                            Quantity = "500 gms"
                        },
                        new
                        {
                            Id = 8,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2074),
                            CategoryId = 1,
                            Name = "Red Rice",
                            PresentCost = 100m,
                            Quantity = "1 kg"
                        },
                        new
                        {
                            Id = 9,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2075),
                            CategoryId = 1,
                            Name = "Ragi Dosa",
                            PresentCost = 100m,
                            Quantity = "1 kg"
                        },
                        new
                        {
                            Id = 10,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2077),
                            CategoryId = 1,
                            Name = "Banana Stem Batter",
                            PresentCost = 120m,
                            Quantity = "1 kg"
                        },
                        new
                        {
                            Id = 11,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2078),
                            CategoryId = 1,
                            Name = "Moringa Dosa",
                            PresentCost = 120m,
                            Quantity = "1 kg"
                        },
                        new
                        {
                            Id = 12,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2080),
                            CategoryId = 1,
                            Name = "Palak Dosa Batter",
                            PresentCost = 120m,
                            Quantity = "1 kg"
                        },
                        new
                        {
                            Id = 13,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2081),
                            CategoryId = 1,
                            Name = "Peanut Dosa Batter",
                            PresentCost = 120m,
                            Quantity = "1 kg"
                        },
                        new
                        {
                            Id = 14,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2083),
                            CategoryId = 1,
                            Name = "Curry Leaf Dosa",
                            PresentCost = 120m,
                            Quantity = "1 kg"
                        },
                        new
                        {
                            Id = 15,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2084),
                            CategoryId = 1,
                            Name = "Multi Dhal / Adai Batter",
                            PresentCost = 120m,
                            Quantity = "1 kg"
                        },
                        new
                        {
                            Id = 16,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2108),
                            CategoryId = 1,
                            Name = "Garlic Dosa Batter",
                            PresentCost = 120m,
                            Quantity = "1 kg"
                        },
                        new
                        {
                            Id = 17,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2110),
                            CategoryId = 1,
                            Name = "Wheat Dosa Batter",
                            PresentCost = 100m,
                            Quantity = "1 kg"
                        },
                        new
                        {
                            Id = 18,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2111),
                            CategoryId = 2,
                            Name = "Coconut Chutney",
                            PresentCost = 30m,
                            Quantity = "100gms"
                        },
                        new
                        {
                            Id = 19,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2113),
                            CategoryId = 2,
                            Name = "Peanut Chutney",
                            PresentCost = 30m,
                            Quantity = "100gms",
                            RevisedCost = 35m
                        },
                        new
                        {
                            Id = 20,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2584),
                            CategoryId = 2,
                            Name = "Tomato Chutney",
                            PresentCost = 30m,
                            Quantity = "100gms",
                            RevisedCost = 35m
                        },
                        new
                        {
                            Id = 21,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2589),
                            CategoryId = 2,
                            Name = "Garlic Chutney",
                            PresentCost = 35m,
                            Quantity = "100gms",
                            RevisedCost = 40m
                        },
                        new
                        {
                            Id = 22,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2591),
                            CategoryId = 2,
                            Name = "Onion Chutney",
                            PresentCost = 30m,
                            Quantity = "100gms",
                            RevisedCost = 35m
                        },
                        new
                        {
                            Id = 23,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2593),
                            CategoryId = 2,
                            Name = "Mint Chutney",
                            PresentCost = 30m,
                            Quantity = "100gms",
                            RevisedCost = 35m
                        },
                        new
                        {
                            Id = 24,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2595),
                            CategoryId = 2,
                            Name = "Chennai Tiffin Sambar",
                            PresentCost = 30m,
                            Quantity = "300gms",
                            RevisedCost = 35m
                        },
                        new
                        {
                            Id = 25,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2597),
                            CategoryId = 2,
                            Name = "Coconut Milk",
                            PresentCost = 100m,
                            Quantity = "300gms"
                        },
                        new
                        {
                            Id = 26,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2598),
                            CategoryId = 2,
                            Name = "Kadala Curry",
                            PresentCost = 100m,
                            Quantity = "350gms",
                            RevisedCost = 105m
                        },
                        new
                        {
                            Id = 27,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2600),
                            CategoryId = 3,
                            Name = "Plain Sevai",
                            PresentCost = 100m,
                            Quantity = "500gms"
                        },
                        new
                        {
                            Id = 28,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2620),
                            CategoryId = 3,
                            Name = "Idiyappam",
                            PresentCost = 15m,
                            Quantity = "1 no"
                        },
                        new
                        {
                            Id = 29,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2622),
                            CategoryId = 3,
                            Name = "Regular Idly",
                            PresentCost = 10m,
                            Quantity = "1 no",
                            RevisedCost = 12m
                        },
                        new
                        {
                            Id = 30,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2624),
                            CategoryId = 3,
                            Name = "Puttu / 1 Cylinder",
                            PresentCost = 80m,
                            Quantity = "1 no",
                            RevisedCost = 90m
                        },
                        new
                        {
                            Id = 31,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2625),
                            CategoryId = 3,
                            Name = "Mini Podi Idly",
                            PresentCost = 100m,
                            Quantity = "30 nos",
                            RevisedCost = 105m
                        },
                        new
                        {
                            Id = 32,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2628),
                            CategoryId = 3,
                            Name = "Mini Idly Sambar",
                            PresentCost = 100m,
                            Quantity = "30 nos",
                            RevisedCost = 105m
                        },
                        new
                        {
                            Id = 33,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2630),
                            CategoryId = 3,
                            Name = "Lemon Sevai",
                            PresentCost = 75m,
                            Quantity = "250gms",
                            RevisedCost = 85m
                        },
                        new
                        {
                            Id = 34,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2632),
                            CategoryId = 3,
                            Name = "Coconut Sevai",
                            PresentCost = 100m,
                            Quantity = "250gms",
                            RevisedCost = 105m
                        },
                        new
                        {
                            Id = 35,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2634),
                            CategoryId = 3,
                            Name = "Tomato Sevai",
                            PresentCost = 100m,
                            Quantity = "250gms",
                            RevisedCost = 105m
                        },
                        new
                        {
                            Id = 36,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2649),
                            CategoryId = 3,
                            Name = "Garlic Sevai",
                            PresentCost = 100m,
                            Quantity = "250gms",
                            RevisedCost = 105m
                        },
                        new
                        {
                            Id = 37,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2651),
                            CategoryId = 3,
                            Name = "Sweet Sevai",
                            PresentCost = 100m,
                            Quantity = "250gms",
                            RevisedCost = 105m
                        },
                        new
                        {
                            Id = 38,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2653),
                            CategoryId = 3,
                            Name = "Puliyogare Sevai",
                            PresentCost = 100m,
                            Quantity = "250gms",
                            RevisedCost = 105m
                        },
                        new
                        {
                            Id = 39,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2656),
                            CategoryId = 4,
                            Name = "Masal Dosa (with Sambar & Chutney)",
                            PresentCost = 65m,
                            Quantity = "1",
                            RevisedCost = 70m
                        },
                        new
                        {
                            Id = 40,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2658),
                            CategoryId = 4,
                            Name = "Puri with Kurma - 3 Pieces",
                            PresentCost = 80m,
                            Quantity = "1",
                            RevisedCost = 90m
                        },
                        new
                        {
                            Id = 41,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2659),
                            CategoryId = 4,
                            Name = "Chapathi",
                            PresentCost = 15m,
                            Quantity = "1"
                        },
                        new
                        {
                            Id = 42,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2661),
                            CategoryId = 4,
                            Name = "Sunday Fuel - Pongal, Vada with Sambar & Chutney (Sunday only)",
                            PresentCost = 80m,
                            Quantity = "1",
                            RevisedCost = 85m
                        },
                        new
                        {
                            Id = 43,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2663),
                            CategoryId = 4,
                            Name = "Thatte Idly, Vada with Sambar & Chutney (Saturday only)",
                            PresentCost = 60m,
                            Quantity = "1",
                            RevisedCost = 65m
                        },
                        new
                        {
                            Id = 44,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2665),
                            CategoryId = 5,
                            Name = "Sambar Podi",
                            PresentCost = 160m,
                            Quantity = "200gms"
                        },
                        new
                        {
                            Id = 45,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2668),
                            CategoryId = 5,
                            Name = "Idili/Dosa Podi",
                            PresentCost = 160m,
                            Quantity = "200gms"
                        },
                        new
                        {
                            Id = 46,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2670),
                            CategoryId = 5,
                            Name = "Gunpowder Podi",
                            PresentCost = 80m,
                            Quantity = "100gms"
                        },
                        new
                        {
                            Id = 47,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2673),
                            CategoryId = 5,
                            Name = "Groundnut Podi",
                            PresentCost = 80m,
                            Quantity = "100gms"
                        },
                        new
                        {
                            Id = 48,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2675),
                            CategoryId = 6,
                            Name = "Grated Coconut",
                            PresentCost = 160m,
                            Quantity = "200gms",
                            RevisedCost = 160m
                        },
                        new
                        {
                            Id = 49,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2677),
                            CategoryId = 7,
                            Name = "Adhirasam (Kajaya)",
                            PresentCost = 60m,
                            Quantity = "Pack of 4",
                            RevisedCost = 65m
                        },
                        new
                        {
                            Id = 50,
                            AddedDate = new DateTime(2026, 4, 28, 14, 19, 27, 244, DateTimeKind.Local).AddTicks(2679),
                            CategoryId = 7,
                            Name = "Thengapal Muruku (Big)",
                            PresentCost = 60m,
                            Quantity = "Pack of 2",
                            RevisedCost = 65m
                        });
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "user");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Society", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Area")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PinCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Societies", "user");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WhatsAppId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", "user");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.UserCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCredentials", "user");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Catalog", b =>
                {
                    b.HasOne("OrderManagement.Domain.Entities.Merchant", "Merchant")
                        .WithMany("Catalogs")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.CatalogItem", b =>
                {
                    b.HasOne("OrderManagement.Domain.Entities.Catalog", "Catalog")
                        .WithMany("Items")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagement.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Catalog");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.CustomerProfile", b =>
                {
                    b.HasOne("OrderManagement.Domain.Entities.MerchantSociety", "MerchantSociety")
                        .WithMany("CustomerProfiles")
                        .HasForeignKey("MerchantSocietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagement.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MerchantSociety");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Merchant", b =>
                {
                    b.HasOne("OrderManagement.Domain.Entities.User", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.MerchantSociety", b =>
                {
                    b.HasOne("OrderManagement.Domain.Entities.Merchant", "Merchant")
                        .WithMany("MerchantSocieties")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagement.Domain.Entities.Society", "Society")
                        .WithMany("MerchantSocieties")
                        .HasForeignKey("SocietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");

                    b.Navigation("Society");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Order", b =>
                {
                    b.HasOne("OrderManagement.Domain.Entities.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OrderManagement.Domain.Entities.MerchantSociety", "MerchantSociety")
                        .WithMany("Orders")
                        .HasForeignKey("MerchantSocietyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OrderManagement.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("MerchantSociety");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("OrderManagement.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.OrderStatusHistory", b =>
                {
                    b.HasOne("OrderManagement.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OrderManagement.Domain.Entities.Order", "Order")
                        .WithMany("StatusHistories")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.OrderTemplate", b =>
                {
                    b.HasOne("OrderManagement.Domain.Entities.Merchant", "Merchant")
                        .WithMany("OrderTemplates")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Payment", b =>
                {
                    b.HasOne("OrderManagement.Domain.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Product", b =>
                {
                    b.HasOne("OrderManagement.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("OrderManagement.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.UserCredential", b =>
                {
                    b.HasOne("OrderManagement.Domain.Entities.User", "User")
                        .WithOne("Credential")
                        .HasForeignKey("OrderManagement.Domain.Entities.UserCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Catalog", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Merchant", b =>
                {
                    b.Navigation("Catalogs");

                    b.Navigation("MerchantSocieties");

                    b.Navigation("OrderTemplates");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.MerchantSociety", b =>
                {
                    b.Navigation("CustomerProfiles");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Society", b =>
                {
                    b.Navigation("MerchantSocieties");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("Credential")
                        .IsRequired();

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
